### ISSUE TITLE
SOS 1.0.0 stops immediately

### ISSUE THREAD

**Issue by mantonovic** [opengeospatial/ets-sos10#10] opened 2020-01-08 14:23 UTC
I'am trying to run tests for istSOS v2.3.3 (an OSGeo incubating project) a software implementing Sensor Observation Service version 1.0.0 (and 2.0.0 which have passed the teamengine tests).

But during the tests for SOS v1.0.0 It stops immediatly during the "sos:Main" tests. I've checked with the 52n reference implementation but the result is the same. It stops immediatly.

I've tried with the production teamengine: https://cite.opengeospatial.org/teamengine and with the beta https://cite.opengeospatial.org/t2 but the result is same.

**URL used** (with and without https):

-  **istSOS**: http://geoservice.ist.supsi.ch/istsos/demo
- **And also 52n**: http://sensorweb.demo.52north.org/52n-sos-webapp/service

Here the logs:
[s0003.zip](https://github.com/opengeospatial/teamengine/files/4035634/s0003.zip)

**Comment by dstenger** [comment] 2020-01-14 13:27
Thank for for reporting.

I moved this issue to tracker of SOS 1.0 test suite.

**Comment by dstenger** [comment] 2020-01-14 13:27
@epicureanism Can you please take a look at the reported problem?

**Comment by arieslai** [comment] 2020-01-15 05:51
@dstenger @lgoltz  There are some Java messages in the file: 
s0003\srv\local\teamengine-prod\TE_BASE\users\istsos\s0003\error_log\log.txt

Could you please check if it is related to team engine or other issues?

**Comment by mantonovic** [comment] 2020-01-16 07:40
line 872 of the mentioned file [1]:

```
Caused by: java.lang.RuntimeException: Failed to parse resource from http://geoservice.ist.supsi.ch/istsos/demo?request=GetCapabilities&service=SOS&AcceptVersions=1.0.0 
 FWK005 parse may not be called while parsing.
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:227)
	... 266 more
```
Can be something related to the Parser?
As found here [2], the exception can be thrown if thread safe precautions are not taken.

[1] s0003\srv\local\teamengine-prod\TE_BASE\users\istsos\s0003\error_log\log.txt
[2] https://prystash.blogspot.com/2012/01/xerces-parsing-and-dreaded-fwk005.html

**Comment by dstenger** [comment] 2020-02-12 10:15
@keshav-nangare Can you please check if this issue is TEAM Engine related?

**Comment by keshavnangare** [comment] 2020-08-21 16:19
@mantonovic 

I have used services provided by you but unable to reproduce the issue. I went through attached session error_log file but when I executed test suite with provided services, did not get any error_log.
Can you please provide steps to reproduce it ?

**Comment by ghobona** [comment] 2021-05-17 19:11
@mantonovic The istSOS service is no longer available, so we are unable to reproduce the issue.

**Comment by ghobona** [comment] 2021-06-30 11:49
@mantonovic The istSOS service is no longer available, so we are unable to reproduce the issue.

We will close this issue on 2021-07-17.

**Closed as completed** 2021-07-05 08:28 UTC
